# Generated by Django 4.2 on 2023-07-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='excel_export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel', models.FileField(upload_to='excel')),
            ],
        ),
    ]
